### ISSUE TITLE
invalid aa in sequence, ignore this peptide!

### ISSUE THREAD

**Issue by lonelu** [pFindStudio/pDeep3#5]
A lot of invalid aa when I try to generate a .msp library. 
[W] invalid aa in sequence 'KLLIYRLSYSULGCYTVR', ignore this peptide!
[W] invalid aa in sequence 'SSUTVCLEAAWLPPKSSYSR', ignore this peptide!
[W] invalid aa in sequence 'KLYAGAILEVCGUKLGR', ignore this peptide!
[W] invalid aa in sequence 'USTCHEIVVTAEEMGEGGNALK', ignore this peptide!
[W] invalid aa in sequence 'GUQSAVNTVICVFGRYK', ignore this peptide!
[W] invalid aa in sequence 'USASAETPILQQSIQUAAPPLR', ignore this peptide!
[W] invalid aa in sequence 'LGINKEEMGLUDSNPK', ignore this peptide!
[W] invalid aa in sequence 'DQDPMLNSNGSVTVVALLQASUYLCILQASK', ignore this peptide!
[W] invalid aa in sequence 'YRGFVCIVTNVASQUGKTEVNYTQLVDLHAR', ignore this peptide!

Not sure what is happening, Assume this should be fine?

**Comment by jalew188** [comment]
> A lot of invalid aa when I try to generate a .msp library.
> [W] invalid aa in sequence 'KLLIYRLSYS**U**LGCYTVR', ignore this peptide!
> [W] invalid aa in sequence 'SS**U**TVCLEAAWLPPKSSYSR', ignore this peptide!
> [W] invalid aa in sequence 'KLYAGAILEVCG**U**KLGR', ignore this peptide!
> [W] invalid aa in sequence '**U**STCHEIVVTAEEMGEGGNALK', ignore this peptide!
> [W] invalid aa in sequence 'G**U**QSAVNTVICVFGRYK', ignore this peptide!
> [W] invalid aa in sequence '**U**SASAETPILQQSIQUAAPPLR', ignore this peptide!
> [W] invalid aa in sequence 'LGINKEEMGL**U**DSNPK', ignore this peptide!
> [W] invalid aa in sequence 'DQDPMLNSNGSVTVVALLQAS**U**YLCILQASK', ignore this peptide!
> [W] invalid aa in sequence 'YRGFVCIVTNVASQ**U**GKTEVNYTQLVDLHAR', ignore this peptide!
> 
> Not sure what is happening, Assume this should be fine?
It is fine.
