### ISSUE TITLE
High memory usage for libary prediction with human database

### ISSUE THREAD

**Issue by lonelu** [pFindStudio/pDeep3#6]
I am using a human database fasta file with decoy attached (~26M).
It takes all memory in windows system with 120G RAM, likely to crash. Am I doing something wrong? the command like this:

python -m pDeep.cmd.generate_predicted_speclib --input human.fasta --output human_lib.msp --varmod Oxidation[M] --instrument QE --ce 30 --min_intensity 0.1 --least_n_peaks 6

**Comment by jalew188** [comment]
In which step?

**Comment by jalew188** [comment]
@lonelu I have tried human.fasta (>6M precursors), it also took >40GB memory (there is only 32GB for my computer). You may need to try to split the target and decoy databases?

**Comment by lonelu** [comment]
Sure. it still running and seems like fine. The RAM usage changes. I will try to split database if this one fails.

**Comment by jalew188** [comment]
@lonelu please `git pull` the latest commit, the memory is saved very well now.

**Comment by lonelu** [comment]
Cool! Fantastic tool.
