### ISSUE TITLE
Workflow for fine-tuning using 6600 .raw data

### ISSUE THREAD

**Issue by brvpuyve** [pFindStudio/pDeep3#8]
Hi pDeep team,

Congratulations on the amazing tool!! 

I just had two questions:
1) What is the best workflow to fine-tune the model starting from SCIEX .wiff files (6600 data)? 

2) I see some extra code was added to create DIA-NN compatible predicted spectral libraries? How does it work? 

Best,
Bart

**Comment by jalew188** [comment]
@brvpuyve 
1. It is complicated for wiff file since pDeep cannot directly access this format currently. We do it as follows:
    Export it into mzml;
    Use pFind3 to identify the mzml, it will generate .pf2 ms file and the identified result;
    psmLabel.exe can read pf2 file and pFind3's identified results
2. For diann format, ```python -m pDeep.cmd.generate_predicted_speclib --output library.diann.csv xxxxx.....(other parameters)```

**Comment by brvpuyve** [comment]
Hi Wen-Fang,

Thanks for the quick reply.
1) I have installed pFind3 and searched some of my DDA files with it. I am just a bit confused with the psmLabel.exe workflow. 
You have to give it the .pf2 file for each data (.wiff) file but what file format does it expect for the identified results (.spectra)? And how can you use the fine-tuning model within the spectral library prediction workflow? 


2) Works perfectly! 

Thank you very much!!

**Comment by jalew188** [comment]
It looks like this:
```
psm_type = pFind3
mode = pDeep
num_psm_file = 1
psm_file1 = D:\...\pFind.spectra
ms2_type = pf2
num_ms2_file = 2
ms2_file1 = D:\...\raw_sample1.pf2
ms2_file2 = D:\...\raw_sample2.pf2
output_folder = D:\...\output
NH3_loss = true
H2O_loss = true
Mod_loss = true
num_ion_type = 2
iontype1 = b|N_term|0
iontype2 = y|C_term|0
num_new_aa = 0
aa1 = c|160.030654|C
aa2 = n|115.026946|N
aa3 = m|147.035405|M
```

**Comment by jalew188** [comment]
@brvpuyve For fine-tuning, I always use ```pDeep.cmd.transfer_train.py``` to fine-tune and save the model, and then use the tuned model for library generation.
